### ISSUE TITLE
Decouple running local binaries and choosing the Node.js version

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/npm-run-path#17]
This library currently does two separate things:
1. Add `[.../]node_modules/.bin` to the `PATH` environment variable, in order to run local binaries
2. Add `dirname(process.execPath)` to the `PATH` environment variable, in order to keep using the same Node.js version

Users cannot currently pick one or the other, they must choose both. It would be nice to provide with a way to optionally pick only one of both. At the moment, users can use the `execPath: string` option, but not disable it. Some potential ideas:
  a. `execPath: string | true | false` option. If `false`, `execPath` is not added. If `true`, only `execPath` is added, not `node_modules/.bin`
  b. `execPath: string | false` + `preferLocal: boolean` options.
  c. `execPath: string` + `keepExecPath: boolean` + `preferLocal: boolean` options.

This is needed for https://github.com/sindresorhus/execa/issues/815

What do you think?

**Comment by sindresorhus** [comment]
I prefer `C`.

**Comment by sindresorhus** [comment]
> keepExecPath: boolean

It's not technically "keeping" `execPath`, it's adding/prepending it.
